// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATxCcNEin_TQUwZ4ummCsQtb9LgTV0wtc',
    appId: '1:572605575375:web:47aeeff6e302ae009207ba',
    messagingSenderId: '572605575375',
    projectId: 'appinventario-d237b',
    authDomain: 'appinventario-d237b.firebaseapp.com',
    databaseURL: 'https://appinventario-d237b-default-rtdb.firebaseio.com',
    storageBucket: 'appinventario-d237b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCtLQKjsNSxpAbvx2F1q4yk5W_7QPVVAw',
    appId: '1:572605575375:android:5efd6a50efc0b9689207ba',
    messagingSenderId: '572605575375',
    projectId: 'appinventario-d237b',
    databaseURL: 'https://appinventario-d237b-default-rtdb.firebaseio.com',
    storageBucket: 'appinventario-d237b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjCWNjc4bdlqeGW7DDj65cphpEw5u_hKo',
    appId: '1:572605575375:ios:445b1224328da15d9207ba',
    messagingSenderId: '572605575375',
    projectId: 'appinventario-d237b',
    databaseURL: 'https://appinventario-d237b-default-rtdb.firebaseio.com',
    storageBucket: 'appinventario-d237b.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjCWNjc4bdlqeGW7DDj65cphpEw5u_hKo',
    appId: '1:572605575375:ios:445b1224328da15d9207ba',
    messagingSenderId: '572605575375',
    projectId: 'appinventario-d237b',
    databaseURL: 'https://appinventario-d237b-default-rtdb.firebaseio.com',
    storageBucket: 'appinventario-d237b.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
